# Generated by Django 4.2.13 on 2024-05-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='source',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
    ]
