# Generated by Django 4.2.13 on 2024-05-29 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_headline_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='is_old',
            field=models.BooleanField(default=False),
        ),
    ]
