# Generated by Django 4.2.13 on 2024-05-29 22:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_headline_is_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2024, 5, 30)),
            preserve_default=False,
        ),
    ]
