# Generated by Django 4.2.13 on 2024-05-30 15:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_headline_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='headline',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
