# Generated by Django 4.2.13 on 2024-05-30 15:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_headline_pub_date_alter_headline_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
