# Generated by Django 4.2.13 on 2024-05-30 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_headline_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headline',
            name='is_old',
        ),
        migrations.RemoveField(
            model_name='headline',
            name='pub_date',
        ),
    ]
