# Generated by Django 4.2.13 on 2024-05-30 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_remove_headline_is_old_remove_headline_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headline',
            name='source',
        ),
    ]
