# Generated by Django 4.2.13 on 2024-05-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_headline_source_alter_headline_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
