# Generated by Django 4.2.13 on 2024-05-30 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_headline_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headline',
            name='post_date',
        ),
    ]
